<a href="https://colab.research.google.com/github/stoicelephant/DIDA325/blob/main/Python_%26_Pandas_Activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Import the Python library used for working with DataFrames.

In [1]:
import pandas as pd

___
##The Bechdel Test

### Load and Examine the Data
The actual dataset can be found at https://raw.githubusercontent.com/fivethirtyeight/data/master/bechdel/movies.csv

In [2]:
bechdel = pd.read_csv("https://raw.githubusercontent.com/fivethirtyeight/data/master/bechdel/movies.csv")

##Exploring

Take a look at the first 8 rows of the dataset.

In [3]:
bechdel.head(8)

,year,imdb,title,test,clean_test,binary,budget,domgross,intgross,code,budget_2013$,domgross_2013$,intgross_2013$,period code,decade code
0,2013,tt1711425,21 &amp; Over,notalk,notalk,FAIL,13000000,25682380.0,42195766.0,2013FAIL,13000000,25682380.0,42195766.0,1.0,1.0
1,2012,tt1343727,Dredd 3D,ok-disagree,ok,PASS,45000000,13414714.0,40868994.0,2012PASS,45658735,13611086.0,41467257.0,1.0,1.0
2,2013,tt2024544,12 Years a Slave,notalk-disagree,notalk,FAIL,20000000,53107035.0,158607035.0,2013FAIL,20000000,53107035.0,158607035.0,1.0,1.0
3,2013,tt1272878,2 Guns,notalk,notalk,FAIL,61000000,75612460.0,132493015.0,2013FAIL,61000000,75612460.0,132493015.0,1.0,1.0
4,2013,tt0453562,42,men,men,FAIL,40000000,95020213.0,95020213.0,2013FAIL,40000000,95020213.0,95020213.0,1.0,1.0
5,2013,tt1335975,47 Ronin,men,men,FAIL,225000000,38362475.0,145803842.0,2013FAIL,225000000,38362475.0,145803842.0,1.0,1.0
6,2013,tt1606378,A Good Day to Die Hard,notalk,notalk,FAIL,92000000,67349198.0,304249198.0,2013FAIL,92000000,67349198.0,304249198.0,1.0,1.0
7,2013,tt2194499,About Time,ok-disagree,ok,PASS,12000000,15323921.0,87324746.0,2013PASS,12000000,15323921.0,87324746.0,1.0,1.0

##Cleaning

Is there any NA data? If you find some, drop them.

In [10]:
bechdel.isna().sum()
bechdel = bechdel.dropna()

I don't like the `code` column. Get rid of it, for good.

In [17]:
bechdel.drop(columns=['code'])

,year,imdb,title,test,clean_test,binary,budget,domgross,intgross,budget_2013$,domgross_2013$,intgross_2013$,period code,decade code
0,2013,tt1711425,21 &amp; Over,notalk,notalk,FAIL,13000000,25682380.0,42195766.0,13000000,25682380.0,42195766.0,1.0,1.0
1,2012,tt1343727,Dredd 3D,ok-disagree,ok,PASS,45000000,13414714.0,40868994.0,45658735,13611086.0,41467257.0,1.0,1.0
2,2013,tt2024544,12 Years a Slave,notalk-disagree,notalk,FAIL,20000000,53107035.0,158607035.0,20000000,53107035.0,158607035.0,1.0,1.0
3,2013,tt1272878,2 Guns,notalk,notalk,FAIL,61000000,75612460.0,132493015.0,61000000,75612460.0,132493015.0,1.0,1.0
4,2013,tt0453562,42,men,men,FAIL,40000000,95020213.0,95020213.0,40000000,95020213.0,95020213.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1610,1990,tt0100403,Predator 2,men,men,FAIL,35000000,28317513.0,54768418.0,62404139,50489429.0,97650742.0,5.0,3.0
1611,1990,tt0100405,Pretty Woman,ok,ok,PASS,14000000,178406268.0,432645872.0,24961656,318093987.0,771396947.0,5.0,3.0
1612,1990,tt0099810,The Hunt for Red October,notalk,notalk,FAIL,30000000,120709866.0,200500000.0,53489262,215222722.0,357486568.0,5.0,3.0
1613,1990,tt0100802,Total Recall,notalk,notalk,FAIL,125000000,58877969.0,198615996.0,222871925,104977970.0,354127435.0,5.0,3.0
1614,1990,tt0100814,Tremors,ok,ok,PASS,10000000,16667084.0,16667084.0,17829754,29717001.0,29717001.0,5.0,3.0

What can we learn about the dataset by running the description of it?

___
### Simple Beginnings
Let's start with a few simple exercises, each of which aren't connected to each other.

Does the movie *Shrek* pass the Bechdel test?

In [25]:
bechdel.loc[bechdel.title == 'Shrek'].test

1196    notalk-disagree
Name: test, dtype: object

Rename the `imdb` column `IMDB_ID`.

In [33]:
bechdel = bechdel.rename(columns = {"imdb":"IMDB_ID"})

What movies in the dataset are from the first year in the dataset? How representative of a sample do you think this dataset is for early years?

In [38]:
bechdel.loc[bechdel.year == bechdel.year.min()]

,year,IMDB_ID,title,test,clean_test,binary,budget,domgross,intgross,code,budget_2013$,domgross_2013$,intgross_2013$,period code,decade code
1600,1990,IMDB_ID,Back to the Future Part III,notalk,notalk,FAIL,40000000,87666629.0,243700000.0,1990FAIL,71319016,156307443.0,434511105.0,5.0,3.0
1601,1990,IMDB_ID,Child&#39;s Play 2,ok,ok,PASS,13000000,26904572.0,34166572.0,1990PASS,23178680,47970190.0,60918157.0,5.0,3.0
1602,1990,IMDB_ID,Dark Angel (I Come in Peace),nowomen,nowomen,FAIL,7000000,4372561.0,4372561.0,1990FAIL,12480828,7796169.0,7796169.0,5.0,3.0
1603,1990,IMDB_ID,Die Hard 2,dubious-disagree,dubious,FAIL,70000000,117323878.0,239814025.0,1990FAIL,124808278,209185588.0,427582507.0,5.0,3.0
1604,1990,IMDB_ID,Edward Scissorhands,ok,ok,PASS,20000000,53976987.0,53976987.0,1990PASS,35659508,96239640.0,96239640.0,5.0,3.0
1605,1990,IMDB_ID,Flatliners,ok,ok,PASS,26000000,61308153.0,61308153.0,1990PASS,46357360,109310929.0,109310929.0,5.0,3.0
1606,1990,IMDB_ID,Ghost,men-disagree,men,FAIL,22000000,217631306.0,517600000.0,1990FAIL,39225459,388031265.0,922868068.0,5.0,3.0
1607,1990,IMDB_ID,Goodfellas,men-disagree,men,FAIL,25000000,46743809.0,46743809.0,1990FAIL,44574385,83343062.0,83343062.0,5.0,3.0
1608,1990,IMDB_ID,Home Alone,men-disagree,men,FAIL,15000000,285761243.0,476684675.0,1990FAIL,26744631,509505267.0,849917050.0,5.0,3.0
1609,1990,IMDB_ID,Nikita,ok,ok,PASS,7000000,5017971.0,5017971.0,1990PASS,12480828,8946919.0,8946919.0,5.0,3.0
1610,1990,IMDB_ID,Predator 2,men,men,FAIL,35000000,28317513.0,54768418.0,1990FAIL,62404139,50489429.0,97650742.0,5.0,3.0
1611,1990,IMDB_ID,Pretty Woman,ok,ok,PASS,14000000,178406268.0,432645872.0,1990PASS,24961656,318093987.0,771396947.0,5.0,3.0
1612,1990,IMDB_ID,The Hunt for Red October,notalk,notalk,FAIL,30000000,120709866.0,200500000.0,1990FAIL,53489262,215222722.0,357486568.0,5.0,3.0
1613,1990,IMDB_ID,Total Recall,notalk,notalk,FAIL,125000000,58877969.0,198615996.0,1990FAIL,222871925,104977970.0,354127435.0,5.0,3.0
1614,1990,IMDB_ID,Tremors,ok,ok,PASS,10000000,16667084.0,16667084.0,1990PASS,17829754,29717001.0,29717001.0,5.0,3.0

Calculate the overall `mean()` budgets in real dollars adjusted for inflation (the _2013. column) for films. In your calculation, divide by 1e6 (or 1000000) so that we can see the result in millions of dollars.

In [53]:
# bechdel.budget_2013.mean()
bechdel['budget_2013$'].mean()

np.float64(57456563.98375)

How many movies in the dataset have each of the possible outcomes for the Bechdel test?

___
### Budgets by Pass/Fail

How do the budgets of movies compare between movies that pass and fail the Bechdel test? To do this, we'll use `group_by()` to group the data by the `clean_test` column, then use `median()` to calculate the median budget (make sure to use the inflation-adjusted `budget_2013.` column).

In [54]:
bechdel.groupby('clean_test')['budget_2013$'].median()

clean_test
dubious    35790994.0
men        39737689.5
notalk     57165293.0
nowomen    44808792.5
ok         31555696.0
Name: budget_2013$, dtype: float64

It'll be a bit easier to make sense of if you also sort to view this in increasing budget order. What trends do you notice?

## Return on Investment
As a starting question, I'd like to re-do some of the analysis done by [this FiveThirtyEight article](https://fivethirtyeight.com/features/the-dollar-and-cents-case-against-hollywoods-exclusion-of-women/): do movies which pass the Bechdel test have a higher return on investment than those that don't? We'll take a couple of steps to get there.

Unfortunately, if you take a peek at the result of `head(bechdel)` the budget columns are characters, not numeric! That's because some of the entries don't have a listed budget or box office take, instead being listed as "#N/A". So, let's remove these.

First, only keep the `year`, `title`, `clean_test`, `budget_2013$`, `intgross_2013$`, and `domgross_2013$` columns. Save the result in a variable caled `profits`.

In [74]:
bechdel_subset = bechdel[['year','title','clean_test','budget_2013$','intgross_2013$','domgross_2013$']]

538 only looked at films after 1990, do let's so the same. Save the result as our profit variable

In [77]:
profits = bechdel_subset[bechdel_subset.year > 1990]

Because typing the `_2013$` at the end of every name is a pain, let's rename() to remove that part so they just have the names `budget`, and so on. Save it in `profits`.

In [87]:
profits = profits.rename(columns = {'budget_2013$':"budget_2013",
                          "domgross_2013$":"domgross_2013",
                          "intgross_2013$":"intgross"})


Finally, let's calculate the domestic return on investment, or `roi`, which is the domestic gross divided by the budget of the film. We'll need to add a column to do this.

In [91]:
profits['roi'] = profits.domgross_2013 / profits.budget_2013
profits

,year,title,clean_test,budget_2013,intgross,domgross_2013,roi
0,2013,21 &amp; Over,notalk,13000000,42195766.0,25682380.0,1.975568
1,2012,Dredd 3D,ok,45658735,41467257.0,13611086.0,0.298105
2,2013,12 Years a Slave,notalk,20000000,158607035.0,53107035.0,2.655352
3,2013,2 Guns,notalk,61000000,132493015.0,75612460.0,1.239549
4,2013,42,men,40000000,95020213.0,95020213.0,2.375505
...,...,...,...,...,...,...,...
1595,1991,Terminator 2: Judgement Day,dubious,171084037,884189932.0,350481895.0,2.048595
1596,1991,The Addams Family,ok,51325211,327629772.0,194184224.0,3.783408
1597,1991,The Naked Gun 2 1/2: The Smell of Fear,notalk,39349328,148724056.0,148724056.0,3.779583
1598,1991,The Silence of the Lambs,ok,34216807,471724395.0,223652543.0,6.536336
1599,1991,White Fang,notalk,23951765,59415931.0,59415931.0,2.480649

Now we're ready to actually summarize the data and get the results we want!
Use `group_by()` to calculate the `mean()` return on investment for each different test result. You can also sort by the `roi` to see them in order a little more clearly. What trends do you see?

In [93]:
profits.groupby('clean_test')['roi'].mean()

clean_test
dubious    3.885551
men        3.318878
notalk     2.548888
nowomen    3.869342
ok         2.830243
Name: roi, dtype: float64