<a href="https://colab.research.google.com/github/stoicelephant/DIDA325/blob/main/week123review.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This is a review file for the first 3 weeeks of stuff that we learned in Dida 325 - Data & Society.\
I'm going to primarily be reviewing the nontrivial things and keepn this document more so as a reference in the future\
\
We learned about Pandas this week so here is an overview of some of the different methods that e learned form the library\
\
Pandas Methods Overview - I am going to list the methods that we have learned and describe how they work, and for methods that I find more interesting I am going to actually show how they work in written code \
\
.dtypes - lists the data types for the different columns in the dataframe\
.columns - lists the columns in the dataframe\
.isnull() - tells you which cells in the dataframe are null\
.isna() - similar to above\
.fillna(value) - allows us to replace the n/a's in our table with some value of our choice
.drop(columns = ['column_name']) or [['column_name']] or .column_name

In [ ]:
import pandas as pd
lb = '-------------'
#this is just some random data i pulled from github
data = pd.read_csv('https://drive.google.com/uc?id=1zO8ekHWx9U7mrbx_0Hoxxu6od7uxJqWw&export=download')
data.head(3)

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/
1,2,1Ef7b82A4CAAD10,Preston,Lozano,Vega-Gentry,East Jimmychester,Djibouti,5153435776,686-620-1820x944,vmata@colon.com,2021-04-23,http://www.hobbs.com/
2,3,6F94879bDAfE5a6,Roy,Berry,Murillo-Perry,Isabelborough,Antigua and Barbuda,+1-539-402-0259,(496)978-3969x58947,beckycarr@hogan.com,2020-03-25,http://www.lawrence.com/

In [ ]:
#these are what I think are the more important

In [ ]:
#the .loc method basically is fed some sore of conditional statement and for all rows which this statement is true the dataframe subsets
data.loc[data.Country == 'Chile']

,Index,Customer Id,First Name,Last Name,Company,City,Country,Phone 1,Phone 2,Email,Subscription Date,Website
0,1,DD37Cf93aecA6Dc,Sheryl,Baxter,Rasmussen Group,East Leonard,Chile,229.077.5154,397.884.0519x718,zunigavanessa@smith.info,2020-08-24,http://www.stephenson.com/

The groupby method follows the format:\
df.groupby(grouping_column)[data_of_interest]\
so for example:\
data.groupby('Country')['Sales'] - will end up combining the sales data for all rows which share a similar country name, and later allow us to apply functions to this data. For example if we apply the .avg method after the groupby we would basically be getting the average number of sales for a given country based on our data which may have many rows of many different and similar countries with sales statistics.